Repository golemfactory/yagna, pull requests merged in 2020-12, with the labels that each got.

#836 [yagna] log version at startup
  core/serv/src/main.rs
Labels: alpha.3

#852 Terminate Agreement tests
  core/market/tests/test_agreement.rs
Labels: t-mkt

#832 TerminateAgreement endpoint
  Cargo.lock
  core/market/src/db/dao/agreement.rs
  core/market/src/db/model/agreement_events.rs
  core/market/src/market.rs
  core/market/src/matcher/resolver.rs
  core/market/src/negotiation/common.rs
  core/market/src/negotiation/error.rs
  core/market/src/negotiation/provider.rs
  core/market/src/negotiation/requestor.rs
  core/market/src/protocol/negotiation.rs
  core/market/src/protocol/negotiation/error.rs
  core/market/src/protocol/negotiation/messages.rs
  core/market/src/protocol/negotiation/provider.rs
  core/market/src/protocol/negotiation/requestor.rs
  core/market/src/rest_api.rs
  core/market/src/rest_api/common.rs
  core/market/src/rest_api/error.rs
  core/market/src/rest_api/provider.rs
  core/market/src/rest_api/requestor.rs
  core/market/src/testing/agreement_utils.rs
  core/market/src/testing/backtrace_util.rs
  core/market/src/testing/mock_identity.rs
  core/market/src/testing/mock_node.rs
  core/market/src/testing/proposal_util.rs
  core/market/tests/test_agreement.rs
  core/market/tests/test_agreement_events.rs
  core/market/tests/test_app_session_id.rs
  core/market/tests/test_initial_proposal.rs
  core/market/tests/test_negotiations.rs
  core/market/tests/test_rest_api.rs
Labels: t-mkt

#858 Reason simplification
  Cargo.lock
  Cargo.toml
  agent/provider/src/market/mock_negotiator.rs
  agent/provider/src/market/negotiator.rs
  agent/provider/src/market/provider_market.rs
  agent/provider/src/market/termination_reason.rs
  core/market/src/db/model/agreement_events.rs
  core/market/tests/test_agreement_events.rs
  core/market/tests/test_rest_api.rs
Labels: t-mkt

#808 Multiple activities per Agreement
  Cargo.lock
  Cargo.toml
  agent/provider/Cargo.toml
  agent/provider/src/execution/task_runner.rs
  agent/provider/src/main.rs
  agent/provider/src/market/config.rs
  agent/provider/src/market/mock_negotiator.rs
  agent/provider/src/market/mod.rs
  agent/provider/src/market/negotiator.rs
  agent/provider/src/market/provider_market.rs
  agent/provider/src/market/termination_reason.rs
  agent/provider/src/payments/payments.rs
  agent/provider/src/provider_agent.rs
  agent/provider/src/startup_config.rs
  agent/provider/src/tasks.rs
  agent/provider/src/tasks/task_info.rs
  agent/provider/src/tasks/task_manager.rs
  agent/provider/src/tasks/task_state.rs
  agent/requestor/Cargo.toml
  agent/requestor/src/main.rs
  core/market/Cargo.toml
  core/market/resolver/src/resolver/properties.rs
  core/market/src/db/model/agreement_events.rs
  core/market/src/market.rs
  core/market/src/negotiation/common.rs
  core/market/src/negotiation/provider.rs
  core/market/src/negotiation/requestor.rs
  core/market/src/protocol/negotiation.rs
  core/market/src/protocol/negotiation/messages.rs
  core/market/src/protocol/negotiation/provider.rs
  core/market/src/protocol/negotiation/requestor.rs
  core/market/src/rest_api.rs
  core/market/src/rest_api/common.rs
  core/market/src/testing/agreement_utils.rs
  core/market/src/utils/display.rs
  core/market/tests/test_agreement.rs
  core/market/tests/test_agreement_events.rs
  core/market/tests/test_rest_api.rs
  core/payment/Cargo.toml
  core/serv/src/main.rs
  exe-unit/Cargo.toml
  utils/agreement-utils/Cargo.toml
  utils/agreement-utils/src/agreement.rs
  utils/agreement-utils/src/lib.rs
  utils/agreement-utils/src/typed_props.rs
Labels: m-provider, t-mkt

#864 Market GSB GetAgreement with Role
  Cargo.lock
  core/activity/src/api.rs
  core/activity/src/common.rs
  core/activity/src/provider/mod.rs
  core/activity/src/provider/service.rs
  core/activity/src/requestor/control.rs
  core/activity/src/requestor/state.rs
  core/market/src/market/agreement.rs
  core/market/tests/test_agreement.rs
  core/model/Cargo.toml
  core/model/src/activity.rs
  core/model/src/market.rs
  core/payment/src/api/provider.rs
  core/payment/src/service.rs
  core/payment/src/utils.rs
Labels: m-activity, m-payment, t-mkt

#859 [Market] Reject Proposal + remove deprecated endpoints + adapt to changed spec
  Cargo.lock
  core/market/Cargo.toml
  core/market/resolver/src/resolver/properties.rs
  core/market/resolver/tests/expression_int.rs
  core/market/src/db/dao.rs
  core/market/src/db/dao/agreement.rs
  core/market/src/db/dao/negotiation_events.rs
  core/market/src/db/dao/proposal.rs
  core/market/src/db/model.rs
  core/market/src/db/model/agreement.rs
  core/market/src/db/model/agreement_events.rs
  core/market/src/db/model/negotiation_events.rs
  core/market/src/db/model/proposal.rs
  core/market/src/db/model/proposal_id.rs
  core/market/src/market/agreement.rs
  core/market/src/negotiation/common.rs
  core/market/src/negotiation/error.rs
  core/market/src/negotiation/provider.rs
  core/market/src/negotiation/requestor.rs
  core/market/src/protocol/discovery/builder.rs
  core/market/src/protocol/negotiation.rs
  core/market/src/protocol/negotiation/error.rs
  core/market/src/protocol/negotiation/messages.rs
  core/market/src/protocol/negotiation/provider.rs
  core/market/src/protocol/negotiation/requestor.rs
  core/market/src/rest_api.rs
  core/market/src/rest_api/common.rs
  core/market/src/rest_api/error.rs
  core/market/src/rest_api/provider.rs
  core/market/src/rest_api/requestor.rs
  core/market/src/testing/agreement_utils.rs
  core/market/src/testing/events_helper.rs
  core/market/src/testing/mock_agreement.rs
  core/market/src/testing/mock_node.rs
  core/market/src/testing/proposal_util.rs
  core/market/tests/test_agreement.rs
  core/market/tests/test_agreement_events.rs
  core/market/tests/test_app_session_id.rs
  core/market/tests/test_cleaner.rs
  core/market/tests/test_cyclic_broadcasts.rs
  core/market/tests/test_initial_proposal.rs
  core/market/tests/test_negotiations.rs
  core/market/tests/test_offer_broadcast.rs
  core/market/tests/test_proposal.rs
  core/market/tests/test_resolver.rs
  core/market/tests/test_rest_api.rs
  core/market/tests/test_subscription.rs
Labels: client API, m-market, t-mkt

#869 AgreementEvents with common fields - compatibility with updated ya-client
  Cargo.lock
  Cargo.toml
  agent/provider/src/market/provider_market.rs
  core/market/Cargo.toml
  core/market/src/db/dao.rs
  core/market/src/db/dao/agreement.rs
  core/market/src/db/dao/agreement_events.rs
  core/market/src/db/dao/negotiation_events.rs
  core/market/src/db/model.rs
  core/market/src/db/model/agreement.rs
  core/market/src/db/model/agreement_events.rs
  core/market/src/db/model/negotiation_events.rs
  core/market/src/negotiation/common.rs
  core/market/src/negotiation/error.rs
  core/market/src/negotiation/provider.rs
  core/market/src/negotiation/requestor.rs
  core/market/src/protocol/discovery/builder.rs
  core/market/src/protocol/negotiation.rs
  core/market/src/rest_api/error.rs
  core/market/src/testing/events_helper.rs
  core/market/src/testing/mock_node.rs
  core/market/tests/test_agreement.rs
  core/market/tests/test_agreement_events.rs
  core/market/tests/test_app_session_id.rs
  core/market/tests/test_cleaner.rs
  core/market/tests/test_cyclic_broadcasts.rs
  core/market/tests/test_initial_proposal.rs
  core/market/tests/test_negotiations.rs
  core/market/tests/test_offer_broadcast.rs
  core/market/tests/test_proposal.rs
  core/market/tests/test_resolver.rs
  core/market/tests/test_rest_api.rs
  core/market/tests/test_subscription.rs
Labels: t-mkt
