Repository golemfactory/yagna, pull requests merged in 2020-10, with the labels that each got.

#515 golem cli
  .github/workflows/rust.yml
  Cargo.lock
  Cargo.toml
  agent/provider/src/cli.rs
  agent/provider/src/hardware.rs
  agent/provider/src/main.rs
  agent/provider/src/market/presets.rs
  agent/provider/src/payments/linear_pricing.rs
  agent/provider/src/provider_agent.rs
  agent/provider/src/startup_config.rs
  core/activity/src/api.rs
  core/activity/src/common.rs
  core/activity/src/dao/activity.rs
  core/serv/src/main.rs
  golem_cli/Cargo.toml
  golem_cli/README.md
  golem_cli/src/appkey.rs
  golem_cli/src/main.rs
  golem_cli/src/service.rs
  golem_cli/src/settings.rs
  golem_cli/src/settings_show.rs
  golem_cli/src/status.rs
  golem_cli/src/utils.rs
Labels: t-exe-unit

#632 Update account not registered error with hint
  core/payment/src/error.rs
Labels: m-payment, ux

#655 Fix net error msg
  core/net/src/service.rs
  service-bus/bus/src/connection.rs
  service-bus/bus/src/error.rs
  service-bus/bus/src/local_router.rs
Labels: alpha.dwa

#668 Provider CLI
  Cargo.lock
  golem_cli/Cargo.toml
  golem_cli/src/banner.txt
  golem_cli/src/command/yagna.rs
  golem_cli/src/main.rs
  golem_cli/src/platform.rs
  golem_cli/src/service.rs
  golem_cli/src/status.rs
  golem_cli/src/terminal.rs
Labels: alpha.dwa

#674 Handle faucet queue requests by waiting
  core/payment-driver/gnt/src/gnt/faucet.rs
Labels: alpha.dwa, m-payment

#653 Build DEB with release-e.
  .ci/pack-build.sh
  .github/workflows/release.yml
  Cargo.toml
  debian/core/preinst
  debian/core/templates
Labels: alpha.dwa

#675 Decentralized Market as default + ver bump + .env-template refresh
  .env-template
  Cargo.lock
  Cargo.toml
  core/market/decentralized/readme.md
Labels: t-mkt

#680 hide access logs for events endpoints
  core/serv/src/main.rs
Labels: alpha.dwa

#687 NGNT driver: wait for ETH before requesting NGNT
  core/payment-driver/gnt/src/gnt/ethereum.rs
  core/payment-driver/gnt/src/gnt/faucet.rs
  core/payment-driver/gnt/src/lib.rs
Labels: alpha.dwa, m-payment

#709 Prekucki/cli invoice status
  Cargo.lock
  core/model/src/payment.rs
  core/payment/Cargo.toml
  core/payment/examples/cancel_invoice.rs
  core/payment/src/cli.rs
  core/payment/src/dao/invoice.rs
  core/payment/src/service.rs
  core/persistence/src/types.rs
  golem_cli/src/command/yagna.rs
  golem_cli/src/status.rs
Labels: alpha.dwa

#689 Exe unit/bugfix/set preset cli
  Cargo.lock
  Cargo.toml
  agent/provider/src/startup_config.rs
  core/model/Cargo.toml
  core/model/src/lib.rs
  core/model/src/payment.rs
  core/payment/Cargo.toml
  core/payment/examples/cancel_invoice.rs
  core/payment/src/cli.rs
  core/payment/src/dao/agreement.rs
  core/payment/src/dao/invoice.rs
  core/payment/src/service.rs
  core/persistence/src/types.rs
  exe-unit/src/handlers/local.rs
  exe-unit/src/lib.rs
  golem_cli/Cargo.toml
  golem_cli/src/command/provider.rs
  golem_cli/src/command/yagna.rs
  golem_cli/src/main.rs
  golem_cli/src/platform.rs
  golem_cli/src/service.rs
  golem_cli/src/settings.rs
  golem_cli/src/setup.rs
  golem_cli/src/status.rs
Labels: alpha.dwa

#716 [Exe-Unit] Fix Supervisor args after recent merges
  agent/provider/src/execution/task_runner.rs
  exe-unit/src/bin.rs
Labels: bug

#442 ExeUnit: streaming ExeScript results
  Cargo.lock
  Cargo.toml
  core/activity/Cargo.toml
  core/activity/migrations/2020-07-15-084557_runtime_event/down.sql
  core/activity/migrations/2020-07-15-084557_runtime_event/up.sql
  core/activity/src/dao/mod.rs
  core/activity/src/dao/runtime_event.rs
  core/activity/src/db/models.rs
  core/activity/src/db/schema.rs
  core/activity/src/requestor/control.rs
  core/market/decentralized/src/testing/mock_net.rs
  core/model/src/activity.rs
  core/net/src/service.rs
  exe-unit/examples/agreement.json
  exe-unit/examples/exe-unit2gsb.rs
  exe-unit/src/error.rs
  exe-unit/src/handlers/local.rs
  exe-unit/src/handlers/rpc.rs
  exe-unit/src/lib.rs
  exe-unit/src/message.rs
  exe-unit/src/output.rs
  exe-unit/src/runtime.rs
  exe-unit/src/runtime/process.rs
  exe-unit/src/service/transfer.rs
  exe-unit/src/state.rs
  service-bus/bus/src/connection.rs
  service-bus/bus/src/local_router.rs
  service-bus/bus/src/remote_router.rs
  service-bus/bus/src/untyped.rs
Labels: t-exe-unit

#749 update provider readme -- define host:port for ya_sb_router
  agent/provider/readme.md
Labels: t-mkt
