Repository golemfactory/yagna, pull requests merged in 2020-11, with the labels that each got.

#751 Provider Agent market refactored
  agent/provider/src/market/provider_market.rs
Labels: t-mkt

#719 Added readme for payment service documenting feature flags
  core/payment/README.md
Labels: m-payment

#758 [act,mkt,pay,agents] adapt to Market API in ya-client
  Cargo.lock
  Cargo.toml
  agent/provider/examples/mock_requestor.rs
  agent/provider/src/market/mock_negotiator.rs
  agent/provider/src/market/negotiator.rs
  agent/provider/src/market/provider_market.rs
  core/activity/src/common.rs
  core/activity/src/dao/event.rs
  core/activity/src/provider/service.rs
  core/activity/src/requestor/control.rs
  core/market/src/db/model/agreement.rs
  core/market/src/db/model/demand.rs
  core/market/src/db/model/offer.rs
  core/market/src/db/model/proposal.rs
  core/market/src/market.rs
  core/market/src/matcher.rs
  core/market/src/matcher/store.rs
  core/market/src/negotiation/common.rs
  core/market/src/negotiation/provider.rs
  core/market/src/negotiation/requestor.rs
  core/market/src/rest_api/provider.rs
  core/market/src/rest_api/requestor.rs
  core/market/src/testing/events_helper.rs
  core/market/src/testing/mock_offer.rs
  core/market/src/testing/proposal_util.rs
  core/market/tests/test_agreement.rs
  core/market/tests/test_initial_proposal.rs
  core/market/tests/test_negotiations.rs
  core/market/tests/test_proposal.rs
  core/market/tests/test_rest_api.rs
  core/market/tests/test_subscription.rs
  core/payment/examples/payment_api.rs
  core/payment/src/api/provider.rs
  core/payment/src/models/agreement.rs
  core/payment/src/service.rs
Labels: t-mkt

#744 Extract payment driver base crate.
  Cargo.lock
  Cargo.toml
  core/payment-driver/base/Cargo.toml
  core/payment-driver/base/src/account.rs
  core/payment-driver/base/src/bus.rs
  core/payment-driver/base/src/driver.rs
  core/payment-driver/base/src/lib.rs
  core/payment-driver/base/src/utils.rs
  core/payment-driver/zksync/Cargo.toml
  core/payment-driver/zksync/src/driver.rs
  core/payment-driver/zksync/src/lib.rs
  core/payment-driver/zksync/src/service.rs
  core/payment-driver/zksync/src/zksync.rs
  core/payment-driver/zksync/src/zksync/faucet.rs
  core/payment-driver/zksync/src/zksync/mod.rs
  core/payment-driver/zksync/src/zksync/signer.rs
  core/payment-driver/zksync/src/zksync/utils.rs
  core/payment-driver/zksync/src/zksync/wallet.rs
Labels: m-payment

#775 Adapt to new Market Api 1.6.1
  Cargo.lock
  Cargo.toml
  agent/provider/src/market/mock_negotiator.rs
  agent/provider/src/market/negotiator.rs
  agent/provider/src/market/provider_market.rs
  core/market/src/db/model/agreement.rs
  core/payment/examples/payment_api.rs
Labels: t-mkt

#779 Add persistence to zksync payment driver
  Cargo.lock
  core/payment-driver/base/Cargo.toml
  core/payment-driver/base/diesel.toml
  core/payment-driver/base/migrations/2020-02-24-085334_init/down.sql
  core/payment-driver/base/migrations/2020-02-24-085334_init/up.sql
  core/payment-driver/base/src/account.rs
  core/payment-driver/base/src/bus.rs
  core/payment-driver/base/src/cron.rs
  core/payment-driver/base/src/dao/error.rs
  core/payment-driver/base/src/dao/mod.rs
  core/payment-driver/base/src/dao/payment.rs
  core/payment-driver/base/src/dao/transaction.rs
  core/payment-driver/base/src/db/mod.rs
  core/payment-driver/base/src/db/models.rs
  core/payment-driver/base/src/db/schema.rs
  core/payment-driver/base/src/driver.rs
  core/payment-driver/base/src/lib.rs
  core/payment-driver/base/src/utils.rs
  core/payment-driver/zksync/Cargo.toml
  core/payment-driver/zksync/src/dao.rs
  core/payment-driver/zksync/src/driver.rs
  core/payment-driver/zksync/src/lib.rs
  core/payment-driver/zksync/src/service.rs
  core/payment-driver/zksync/src/zksync/wallet.rs
  core/payment/examples/payment_api.rs
  core/serv/src/main.rs
Labels: m-payment

#782 Wait with CreateActivity until Task will be initialized
  agent/provider/src/task_manager.rs
  agent/provider/src/task_state.rs
Labels: m-provider

#787 golemsp stop + status version
  Cargo.lock
  Cargo.toml
  agent/provider/Cargo.toml
  agent/provider/src/main.rs
  core/serv/src/main.rs
  golem_cli/Cargo.toml
  golem_cli/build.rs
  golem_cli/src/command/yagna.rs
  golem_cli/src/main.rs
  golem_cli/src/service.rs
  golem_cli/src/status.rs
  utils/process/Cargo.toml
  utils/process/src/lib.rs
  utils/process/src/lock.rs
Labels: alpha.3

#772 Destroy ExeUnits on provider shutdown
  agent/provider/src/execution/mod.rs
  agent/provider/src/execution/task_runner.rs
  agent/provider/src/provider_agent.rs
Labels: alpha.3

#797 Add re-try to zksync faucet request
  core/payment-driver/zksync/src/zksync/faucet.rs
  core/payment-driver/zksync/src/zksync/wallet.rs
Labels: alpha.3

#811 Increment nonce locally for each batch of transactions
  core/payment-driver/zksync/src/driver.rs
  core/payment-driver/zksync/src/zksync/wallet.rs
Labels: alpha.3, bug

#809 Yagna buildtime version
  Cargo.lock
  agent/provider/src/startup_config.rs
  agent/requestor/src/main.rs
  core/serv/src/main.rs
  exe-unit/src/bin.rs
  golem_cli/Cargo.toml
  golem_cli/src/banner.txt
  golem_cli/src/main.rs
  golem_cli/src/status.rs
  service-bus/router/examples/ya_sb_router.rs
  utils/compile-time-utils/Cargo.toml
  utils/compile-time-utils/build.rs
  utils/compile-time-utils/src/lib.rs
Labels: alpha.3, enhancement, ux

#793 Add AppSessionId
  Cargo.lock
  Cargo.toml
  core/market/Cargo.toml
  core/market/migrations/2020-05-15-093513_init-db/down.sql
  core/market/migrations/2020-10-04-190200_agreement_events/down.sql
  core/market/migrations/2020-10-04-190200_agreement_events/up.sql
  core/market/src/config.rs
  core/market/src/db/dao.rs
  core/market/src/db/dao/agreement.rs
  core/market/src/db/dao/agreement_events.rs
  core/market/src/db/dao/cleaner.rs
  core/market/src/db/dao/negotiation_events.rs
  core/market/src/db/model.rs
  core/market/src/db/model/agreement.rs
  core/market/src/db/model/agreement_events.rs
  core/market/src/db/model/negotiation_events.rs
  core/market/src/db/model/proposal.rs
  core/market/src/db/model/proposal_id.rs
  core/market/src/db/model/subscription_id.rs
  core/market/src/db/schema.rs
  core/market/src/lib.rs
  core/market/src/market.rs
  core/market/src/matcher/handlers.rs
  core/market/src/negotiation/common.rs
  core/market/src/negotiation/error.rs
  core/market/src/negotiation/notifier.rs
  core/market/src/negotiation/provider.rs
  core/market/src/negotiation/requestor.rs
  core/market/src/protocol/negotiation/error.rs
  core/market/src/protocol/negotiation/provider.rs
  core/market/src/rest_api.rs
  core/market/src/rest_api/common.rs
  core/market/src/rest_api/error.rs
  core/market/src/rest_api/provider.rs
  core/market/src/rest_api/requestor.rs
  core/market/src/testing.rs
  core/market/src/testing/agreement_utils.rs
  core/market/src/testing/dao.rs
  core/market/src/testing/events_helper.rs
  core/market/src/testing/mock_agreement.rs
  core/market/src/testing/mock_offer.rs
  core/market/src/testing/proposal_util.rs
  core/market/src/utils.rs
  core/market/src/utils/display.rs
  core/market/tests/test_agreement.rs
  core/market/tests/test_agreement_events.rs
  core/market/tests/test_app_session_id.rs
  core/market/tests/test_initial_proposal.rs
  core/market/tests/test_rest_api.rs
  utils/diesel-utils/Cargo.toml
  utils/diesel-utils/src/lib.rs
Labels: t-mkt

#831 Merge SGX metrics fix present in master
  exe-unit/src/runtime/process.rs
  exe-unit/src/service/metrics.rs
Labels: alpha.3

#834 [ya-prov] break agreement if no activity for 90s
  agent/provider/src/task_manager.rs
  agent/provider/src/task_state.rs
Labels: alpha.3, bug, m-provider
