Repository golemfactory/yagna, pull requests merged in 2021-03, with the labels that each got.

#1105 Rename query's "pollTimeout" to "timeout"
  Cargo.lock
  Cargo.toml
  core/activity/src/common.rs
  core/activity/src/provider/mod.rs
  core/payment/src/api/debit_notes.rs
  core/payment/src/api/invoices.rs
  core/payment/src/api/payments.rs
Labels: bug

#1109 Provider agent: process activity events sequentially
  agent/provider/src/provider_agent.rs
  utils/actix_utils/src/actix_handler.rs
Labels: beta.1, bug

#1106 Provider - terminate agreement on unreachable requestor
  agent/provider/src/market/termination_reason.rs
  agent/provider/src/payments/agreement.rs
  agent/provider/src/payments/payments.rs
  utils/std-utils/src/result.rs
Labels: m-provider

#1102 Provider - fix debit notes property
  agent/provider/src/payments/model.rs
Labels: bug, m-provider

#1116 Provider - decrease Agreement expiration in case of keep alive enabled
  agent/provider/src/market/negotiator/factory.rs
Labels: m-provider

#1002 Track Offers/Demand expirations
  Cargo.lock
  agent/provider/Cargo.toml
  agent/provider/src/payments/mod.rs
  agent/provider/src/payments/payments.rs
  core/market/Cargo.toml
  core/market/src/config.rs
  core/market/src/db/dao.rs
  core/market/src/db/dao/demand.rs
  core/market/src/market.rs
  core/market/src/matcher.rs
  core/market/src/matcher/error.rs
  core/market/src/matcher/store.rs
  utils/actix_utils/Cargo.toml
  utils/actix_utils/src/actix_signal.rs
  utils/actix_utils/src/deadline_checker.rs
  utils/actix_utils/src/lib.rs
Labels: t-mkt

#1117 Configurable Agreement idle timeout
  agent/provider/src/provider_agent.rs
  agent/provider/src/startup_config.rs
  agent/provider/src/tasks.rs
  agent/provider/src/tasks/config.rs
  agent/provider/src/tasks/task_info.rs
  agent/provider/src/tasks/task_manager.rs
Labels: m-provider

#1126 Removed 'glmsync' from help messages
  core/model/src/payment.rs
Labels: beta.1

#1133 Fix: Change metric from driver to platform
  core/payment/src/processor.rs
Labels: m-metrics

#1134 Market/timeout gsb get remote offers fix + removed cache steps from CI
  .github/workflows/rust.yml
Labels: beta.1.patch, m-market, t-mkt

#1120 Timeout gsb get remote offers
  .github/workflows/rust.yml
  core/market/src/protocol/discovery.rs
  core/market/tests/test_offer_broadcast.rs
Labels: beta.1.patch, m-market

#1108 Provider - fix idle agreements termination
  agent/provider/src/execution/mod.rs
  agent/provider/src/execution/task_runner.rs
  agent/provider/src/market/provider_market.rs
  agent/provider/src/market/termination_reason.rs
  agent/provider/src/payments/agreement.rs
  agent/provider/src/payments/payment_checker.rs
  agent/provider/src/payments/payments.rs
  agent/provider/src/provider_agent.rs
  agent/provider/src/startup_config.rs
  agent/provider/src/tasks.rs
  agent/provider/src/tasks/config.rs
  agent/provider/src/tasks/task_info.rs
  agent/provider/src/tasks/task_manager.rs
  agent/provider/src/tasks/task_state.rs
  utils/actix_utils/src/actix_signal.rs
Labels: beta.1.patch

#1082 fix for: error during normal operation
  core/activity/examples/activity_provider_api.rs
  core/activity/examples/activity_requestor_api.rs
  core/identity/src/dao/appkey.rs
  core/identity/src/dao/identity.rs
  core/persistence/src/executor.rs
Labels: beta.1.patch

#1121 we have a new yacn server
  agent/provider/readme.md
  core/market/resolver/tests/expression_resolve.rs
  core/market/resolver/tests/sample/mod.rs
  core/serv/README.md
  exe-unit/examples/agreement.json
  exe-unit/examples/commands.json
  test-utils/linux-test-scripts/test1/agreement.json
  test-utils/linux-test-scripts/test1/exe_script.json
  test-utils/win-test-scripts/test1/README.md
  test-utils/win-test-scripts/test1/agreement.json
  test-utils/win-test-scripts/test1/exe_script.json
  utils/agreement-utils/tests/agreement-9ce65424.json
Labels: beta.1, beta.1.patch

#1182 Provider - send less DebitNotes
  agent/provider/readme.md
  agent/provider/src/market/negotiator/builtin/expiration.rs
  agent/provider/src/market/negotiator/factory.rs
  agent/provider/src/payments/pricing.rs
Labels: m-provider

#1184 ZkSync: Check balance before operations
  core/payment-driver/zksync/src/zksync/wallet.rs
Labels: beta.1.patch.2, bug, m-payment
