Repository golemfactory/yagna, pull requests merged in 2021-01, with the labels that each got.

#830 Clean provider data dir on start / on demand
  Cargo.lock
  agent/provider/Cargo.toml
  agent/provider/src/dir.rs
  agent/provider/src/main.rs
  agent/provider/src/startup_config.rs
Labels: m-provider

#767 Runtime API: propagate process status
  Cargo.lock
  exe-unit/runtime-api/Cargo.toml
  exe-unit/runtime-api/src/server.rs
  exe-unit/runtime-api/src/server/client.rs
  exe-unit/src/runtime/process.rs
Labels: t-exe-unit

#873 Respawn proposal after termination
  core/market/src/db/dao/agreement.rs
  core/market/src/db/dao/negotiation_events.rs
  core/market/src/market.rs
  core/market/src/negotiation/common.rs
  core/market/src/negotiation/error.rs
  core/market/src/negotiation/provider.rs
  core/market/src/negotiation/requestor.rs
  core/market/src/rest_api/common.rs
  core/market/src/rest_api/error.rs
  core/market/src/testing/agreement_utils.rs
  core/market/src/testing/events_helper.rs
  core/market/src/testing/proposal_util.rs
  core/market/tests/test_agreement.rs
  core/market/tests/test_agreement_events.rs
  core/market/tests/test_initial_proposal.rs
  core/market/tests/test_negotiations.rs
  core/market/tests/test_proposal.rs
  core/market/tests/test_rest_api.rs
Labels: t-mkt

#897 Provider - check debit notes acceptance
  Cargo.lock
  agent/provider/Cargo.toml
  agent/provider/src/display.rs
  agent/provider/src/execution/task_runner.rs
  agent/provider/src/main.rs
  agent/provider/src/market/config.rs
  agent/provider/src/market/mock_negotiator.rs
  agent/provider/src/market/mod.rs
  agent/provider/src/market/negotiator.rs
  agent/provider/src/market/negotiator/accept_all.rs
  agent/provider/src/market/negotiator/builtin.rs
  agent/provider/src/market/negotiator/builtin/expiration.rs
  agent/provider/src/market/negotiator/builtin/max_agreements.rs
  agent/provider/src/market/negotiator/common.rs
  agent/provider/src/market/negotiator/component.rs
  agent/provider/src/market/negotiator/composite.rs
  agent/provider/src/market/negotiator/factory.rs
  agent/provider/src/market/provider_market.rs
  agent/provider/src/market/termination_reason.rs
  agent/provider/src/payments/agreement.rs
  agent/provider/src/payments/factory.rs
  agent/provider/src/payments/mod.rs
  agent/provider/src/payments/model.rs
  agent/provider/src/payments/payment_checker.rs
  agent/provider/src/payments/payments.rs
  agent/provider/src/payments/pricing.rs
  agent/provider/src/provider_agent.rs
  agent/provider/src/startup_config.rs
  agent/provider/src/tasks/task_manager.rs
  core/market/resolver/src/lib.rs
  core/market/resolver/tests/match_demand_offer.rs
  core/market/src/db/model/proposal.rs
  core/market/src/negotiation/common.rs
  core/market/src/negotiation/error.rs
  core/market/src/utils/display.rs
  utils/actix_utils/Cargo.toml
  utils/actix_utils/src/actix_signal.rs
  utils/agreement-utils/src/agreement.rs
Labels: m-provider

#974 ERC-20 payment driver: added network field to transaction
  Cargo.lock
  core/payment-driver/gnt/Cargo.toml
  core/payment-driver/gnt/migrations/2021-01-18-154920_network_id/down.sql
  core/payment-driver/gnt/migrations/2021-01-18-154920_network_id/up.sql
  core/payment-driver/gnt/src/dao/transaction.rs
  core/payment-driver/gnt/src/gnt/sender.rs
  core/payment-driver/gnt/src/lib.rs
  core/payment-driver/gnt/src/models.rs
  core/payment-driver/gnt/src/networks.rs
  core/payment-driver/gnt/src/schema.rs
  core/payment-driver/gnt/src/utils.rs
  core/payment/examples/debit_note_flow.rs
  core/payment/examples/invoice_flow.rs
Labels: alpha.4, bug

#978 ZkSync driver: cron job mutexes
  Cargo.lock
  core/payment-driver/base/Cargo.toml
  core/payment-driver/base/src/cron.rs
Labels: alpha.4, bug

#979 GSB: subscriptions on reconnect fix
  Cargo.lock
  Cargo.toml
  core/activity/Cargo.toml
  core/identity/Cargo.toml
  core/model/src/net.rs
  core/net/Cargo.toml
  core/net/src/api.rs
  core/net/src/handler.rs
  core/net/src/lib.rs
  core/net/src/service.rs
  core/payment/Cargo.toml
  core/serv-api/web/Cargo.toml
  exe-unit/Cargo.toml
Labels: alpha.4, bug

#982 Payment service: fixed computing payment amounts
  core/model/src/payment.rs
  core/payment/migrations/2021-01-28-102818_scheduled_amount/down.sql
  core/payment/migrations/2021-01-28-102818_scheduled_amount/up.sql
  core/payment/src/api/debit_notes.rs
  core/payment/src/api/invoices.rs
  core/payment/src/dao/activity.rs
  core/payment/src/dao/agreement.rs
  core/payment/src/dao/order.rs
  core/payment/src/dao/payment.rs
  core/payment/src/models/activity.rs
  core/payment/src/models/agreement.rs
  core/payment/src/processor.rs
  core/payment/src/schema.rs
  core/persistence/src/executor.rs
Labels: alpha.4, bug

#983 Fix for CLI's "activity status" and flexbuffers
  core/activity/src/provider/service.rs
  core/model/src/activity.rs
Labels: alpha.4, bug
