Repository golemfactory/yagna, pull requests merged in 2021-07, with the labels that each got.

#1465 Disable sending foreign Offers
  core/market/src/matcher/cyclic.rs
  core/market/tests/test_cyclic_broadcasts.rs
Labels: m-market, t-mkt

#1458 Http file transfer: handle complete temporary files
  exe-unit/examples/transfer_resume.rs
  exe-unit/src/service/transfer.rs
  utils/transfer/src/http.rs
  utils/transfer/src/lib.rs
Labels: beta.2.patch.2

#1478 PaymentProcessor: assert `orders` size before calling `unwrap`
  core/payment/src/processor.rs
Labels: bug

#1502 Deb version fix via `ya-compile-time-utils`
  Cargo.lock
  Cargo.toml
  agent/provider/Cargo.toml
  core/gftp/Cargo.toml
  core/version/Cargo.toml
  core/version/src/db/dao.rs
  core/version/src/db/model.rs
  core/version/src/github.rs
  exe-unit/Cargo.toml
  golem_cli/Cargo.toml
  golem_cli/src/main.rs
  golem_cli/src/status.rs
  utils/compile-time-utils/Cargo.toml
  utils/compile-time-utils/src/lib.rs
Labels: beta.2.patch.3

#1501 v0.7.3: ya-sb-router 0.4.5, ya-service-bus 0.4.10
  Cargo.lock
Labels: beta.2.patch.3

#1536 [CI] Always run Market test suite
  .github/workflows/rust.yml
Labels: m-CI

#1538 [CI] Always run Market test suite also on release/v0.7
  .github/workflows/rust.yml
  core/market/tests/test_initial_proposal.rs
Labels: m-CI
