Repository golemfactory/yagna, pull requests merged in 2021-11, with the labels that each got.

#1642 Polygon payment support
  core/model/src/driver.rs
  core/payment-driver/base/migrations/2021-10-13-033400_payment_driver_improvements/down.sql
  core/payment-driver/base/migrations/2021-10-13-033400_payment_driver_improvements/up.sql
  core/payment-driver/base/src/cron.rs
  core/payment-driver/base/src/dao/payment.rs
  core/payment-driver/base/src/dao/transaction.rs
  core/payment-driver/base/src/db/models.rs
  core/payment-driver/base/src/db/schema.rs
  core/payment-driver/base/src/utils.rs
  core/payment-driver/erc20/Readme.md
  core/payment-driver/erc20/src/dao.rs
  core/payment-driver/erc20/src/driver.rs
  core/payment-driver/erc20/src/driver/cli.rs
  core/payment-driver/erc20/src/driver/cron.rs
  core/payment-driver/erc20/src/erc20/eth_utils.rs
  core/payment-driver/erc20/src/erc20/ethereum.rs
  core/payment-driver/erc20/src/erc20/faucet.rs
  core/payment-driver/erc20/src/erc20/mod.rs
  core/payment-driver/erc20/src/erc20/transaction.rs
  core/payment-driver/erc20/src/erc20/utils.rs
  core/payment-driver/erc20/src/erc20/wallet.rs
  core/payment-driver/erc20/view_transactions.sql
  core/payment-driver/zksync/src/dao.rs
  core/payment-driver/zksync/src/driver.rs
  core/payment-driver/zksync/src/zksync/wallet.rs
  core/payment/src/cli.rs
  core/payment/src/wallet.rs
Labels: beta.4

#1650 Make erc20 the default driver. Enable polygon.
  core/model/src/payment.rs
  core/payment/src/lib.rs
  golem_cli/src/command/yagna.rs
  golem_cli/src/service.rs
  golem_cli/src/status.rs
  goth_tests/domain/ya-provider/goth-config.yml
  goth_tests/poetry.lock
  goth_tests/pyproject.toml
Labels: yagna-v0.9, beta.4

#1726 Scx1332/payment driver fix critical error
  core/payment-driver/erc20/src/erc20/wallet.rs
Labels: bug, yagna-v0.9

#1731 deb: subsidy terms of use
  Cargo.toml
  debian/provider/preinst
  debian/provider/templates
Labels: yagna-v0.9
