Repository golemfactory/yagna, pull requests merged in 2021-06, with the labels that each got.

#1386 fix typos
  agent/provider/examples/mock_requestor.rs
  core/market/resolver/tests/expression_int.rs
  core/payment-driver/erc20/src/erc20/utils.rs
  core/payment-driver/erc20/src/service.rs
  core/payment-driver/zksync/src/service.rs
  docs/service-bus/ysb-api-concept.md
Labels: slacktime

#1384 ExeUnit Supervisor: ProcessStatus handling tweaks (incl. fixes)
  Cargo.lock
  exe-unit/Cargo.toml
  exe-unit/src/message.rs
  exe-unit/src/runtime/event.rs
  exe-unit/src/runtime/process.rs
Labels: beta.2

#1392 [mkt] cease rebroadcast
  core/market/src/protocol/discovery.rs
Labels: beta.2

#1401 Fix Mkt Bcast metrics
  core/market/src/matcher.rs
  core/market/src/matcher/handlers.rs
  core/market/src/protocol/discovery.rs
  core/metrics/src/pusher.rs
Labels: beta.2, beta.2.patch.1, m-market, m-metrics

#1259 Test provider breaking Agreement
  goth_tests/domain/ya-provider/assets/goth-config.yml
  goth_tests/domain/ya-provider/assets/provider/hardware.json
  goth_tests/domain/ya-provider/assets/provider/presets.json
  goth_tests/domain/ya-provider/test_provider_break_agreement.py
  goth_tests/domain/ya-provider/test_provider_multi_activity.py
  goth_tests/helpers/activity.py
  goth_tests/poetry.lock
  goth_tests/pyproject.toml
Labels: m-provider

#1406 Provider - fix proposal renegotiations
  agent/provider/src/display.rs
  agent/provider/src/market/negotiator/common.rs
  agent/provider/src/market/negotiator/composite.rs
  agent/provider/src/market/provider_market.rs
Labels: beta.2.patch.1

#1407 Interruptable network initialization
  core/net/src/handler.rs
  core/net/src/service.rs
Labels: beta.2.patch.1

#1412 Resumable HTTP transfers
  Cargo.lock
  exe-unit/Cargo.toml
  exe-unit/examples/transfer_resume.rs
  exe-unit/examples/transfer_retry.rs
  exe-unit/src/service/transfer.rs
  exe-unit/src/util/cache.rs
  exe-unit/src/util/mod.rs
  utils/process/src/lib.rs
  utils/transfer/Cargo.toml
  utils/transfer/examples/gftp.rs
  utils/transfer/examples/transfer-archive.rs
  utils/transfer/src/error.rs
  utils/transfer/src/file.rs
  utils/transfer/src/gftp.rs
  utils/transfer/src/http.rs
  utils/transfer/src/lib.rs
  utils/transfer/src/location.rs
  utils/transfer/src/retry.rs
  utils/transfer/src/util.rs
Labels: beta.2.patch.1

#1435 Constraint resolver: support LDAP true and false filters
  core/market/resolver/src/resolver/ldap_parser.rs
  core/market/resolver/tests/expression_resolve.rs
Labels: beta.2.patch.1

#1436 fix: ya-service-bus 0.4.9 - stop reconnecting on sigint
  Cargo.lock
  Cargo.toml
  agent/provider/Cargo.toml
  core/net/Cargo.toml
Labels: beta.2.patch.1

#1446 Fix for requestor's activity usage endpoint
  core/activity/src/api.rs
Labels: beta.2.patch.2, bug

#1454 Provider will resend invoice 5 times in first 30s
  agent/provider/src/payments/payments.rs
Labels: m-provider
