Repository golemfactory/yagna, pull requests merged in 2021-05, with the labels that each got.

#1307 Exe unit/log err better ux
  exe-unit/src/runtime/process.rs
  utils/transfer/src/error.rs
Labels: beta.2, logs, ux

#1314 Runtime API service: refactor run_async's factory to FnOnce
  Cargo.lock
  exe-unit/runtime-api/Cargo.toml
  exe-unit/runtime-api/src/server/service.rs
Labels: m-exe-unit

#1312 Market/config upgrade
  Cargo.lock
  core/market/Cargo.toml
  core/market/src/config.rs
  core/market/src/db/dao/agreement.rs
  core/market/src/db/dao/cleaner.rs
  core/market/src/db/dao/negotiation_events.rs
  core/market/src/lib.rs
  core/market/src/market.rs
  core/market/src/testing.rs
  core/market/src/testing/mock_node.rs
  core/market/tests/test_cleaner.rs
  core/market/tests/test_cyclic_broadcasts.rs
  core/market/tests/test_negotiations.rs
  core/market/tests/test_offer_broadcast.rs
  core/market/tests/test_rest_api.rs
Labels: beta.1.patch.5, m-market

#1320 [golemsp] improve error UX
  golem_cli/src/command/yagna.rs
Labels: ux

#1324 [golemsp] fix broken default_id
  golem_cli/src/command/yagna.rs
Labels: beta.1.patch.5, bug, m-provider

#1150 Restart negotiations
  core/market/src/db/dao/proposal.rs
  core/market/src/db/model/proposal.rs
  core/market/src/negotiation/common.rs
  core/market/tests/test_negotiations.rs
Labels: t-mkt

#1341 Sync release v0.6 to master
  .github/workflows/rust.yml
  .github/workflows/sgx.yml
  Cargo.lock
  Cargo.toml
  core/market/Cargo.toml
  core/market/src/config.rs
  core/market/src/db/dao/agreement.rs
  core/market/src/db/dao/cleaner.rs
  core/market/src/db/dao/negotiation_events.rs
  core/market/src/market.rs
  core/market/src/matcher.rs
  core/market/src/protocol/discovery.rs
  core/market/src/testing/mock_node.rs
  core/market/tests/test_cleaner.rs
  core/net/Cargo.toml
  core/net/src/handler.rs
  core/payment/src/api/debit_notes.rs
  core/payment/src/api/invoices.rs
  core/payment/src/dao/invoice.rs
  core/payment/src/models/invoice.rs
  core/payment/src/service.rs
  core/payment/src/utils.rs
  exe-unit/Cargo.toml
  exe-unit/examples/debug-runtime.rs
  exe-unit/runtime-api/Cargo.toml
  exe-unit/runtime-api/examples/runtime-server-mock.rs
  exe-unit/runtime-api/src/server.rs
  exe-unit/runtime-api/src/server/client.rs
  exe-unit/runtime-api/src/server/service.rs
  exe-unit/src/runtime/event.rs
  golem_cli/src/command/yagna.rs
  utils/compile-time-utils/Cargo.toml
Labels: beta.2

#1327 Bump ya-sb-router and actix to 0.10
  Cargo.lock
  Cargo.toml
  core/payment-driver/base/Cargo.toml
  core/payment-driver/dummy/Cargo.toml
  core/payment-driver/gnt/Cargo.toml
  core/serv-api/web/examples/auth_middleware.rs
  exe-unit/Cargo.toml
  exe-unit/runtime-api/Cargo.toml
  exe-unit/runtime-api/src/server/codec.rs
  exe-unit/src/handlers/local.rs
  utils/process/Cargo.toml
  utils/transfer/Cargo.toml
Labels: beta.1.patch.6

#1315 ExeUnit Supervisor: support self-contained runtimes ("services")
  exe-unit/examples/transfer.rs
  exe-unit/examples/transfer_abort.rs
  exe-unit/src/agreement.rs
  exe-unit/src/bin.rs
  exe-unit/src/handlers/local.rs
  exe-unit/src/lib.rs
  exe-unit/src/message.rs
  exe-unit/src/runtime.rs
  exe-unit/src/runtime/process.rs
  exe-unit/src/service/transfer.rs
  exe-unit/src/state.rs
Labels: beta.2
