Repository golemfactory/yagna, pull requests merged in 2021-02, with the labels that each got.

#995 Market - disable respawn proposal
  core/market/src/negotiation/common.rs
  core/market/tests/test_initial_proposal.rs
Labels: t-mkt

#1014 Approval races - fix agreements locks
  core/market/src/negotiation/common.rs
  core/market/src/negotiation/provider.rs
  core/market/src/negotiation/requestor.rs
  core/market/src/utils/agreement_lock.rs
Labels: t-mkt

#1003 Safely decode received payment details
  core/payment/src/dao/payment.rs
  core/payment/src/models/payment.rs
Labels: beta.1, m-payment

#997 Provider - prepare to agreement approval
  Cargo.lock
  agent/provider/Cargo.toml
  agent/provider/src/execution/task_runner.rs
  agent/provider/src/market/provider_market.rs
  agent/provider/src/payments/payments.rs
  agent/provider/src/tasks/task_manager.rs
  utils/std-utils/src/result.rs
Labels: t-mkt

#1015 Market -- approval ack
  Cargo.lock
  agent/provider/Cargo.toml
  agent/provider/src/execution/task_runner.rs
  agent/provider/src/market/provider_market.rs
  agent/provider/src/payments/payments.rs
  agent/provider/src/tasks/task_manager.rs
  core/market/migrations/2020-10-04-190200_agreement_events/up.sql
  core/market/src/db/dao/agreement.rs
  core/market/src/db/model/agreement.rs
  core/market/src/db/model/agreement_events.rs
  core/market/src/negotiation/common.rs
  core/market/src/negotiation/error.rs
  core/market/src/negotiation/notifier.rs
  core/market/src/negotiation/provider.rs
  core/market/src/negotiation/requestor.rs
  core/market/src/protocol/negotiation.rs
  core/market/src/protocol/negotiation/error.rs
  core/market/src/protocol/negotiation/messages.rs
  core/market/src/protocol/negotiation/provider.rs
  core/market/src/protocol/negotiation/requestor.rs
  core/market/src/rest_api/error.rs
  core/market/src/rest_api/requestor.rs
  core/market/src/testing/events_helper.rs
  core/market/src/testing/mock_node.rs
  core/market/tests/test_agreement.rs
  utils/std-utils/src/result.rs
Labels: t-mkt

#1025 log colors + golemsp: run args fix & status determine network
  Cargo.lock
  agent/provider/Cargo.toml
  agent/provider/src/cli.rs
  agent/provider/src/execution/exeunits_registry.rs
  agent/provider/src/hardware.rs
  agent/provider/src/main.rs
  agent/provider/src/market/presets.rs
  agent/provider/src/provider_agent.rs
  exe-unit/Cargo.toml
  exe-unit/src/bin.rs
  golem_cli/Cargo.toml
  golem_cli/src/command/provider.rs
  golem_cli/src/main.rs
  golem_cli/src/service.rs
  golem_cli/src/setup.rs
  golem_cli/src/status.rs
  utils/file-logging/Cargo.toml
  utils/file-logging/src/lib.rs
Labels: t-mkt

#1024 Provider - agreement pretty display release
  agent/provider/src/display.rs
  agent/provider/src/execution/task_runner.rs
  agent/provider/src/market/negotiator/composite.rs
  agent/provider/src/market/provider_market.rs
  utils/agreement-utils/src/agreement.rs
  utils/agreement-utils/src/typed_props.rs
Labels: t-mkt

#1033 Provider - fix termination attempts in terminated state
  agent/provider/src/tasks/task_manager.rs
Labels: m-provider

#1068 DNS resolve in faucet requests
  Cargo.lock
  core/net/src/service.rs
  core/payment-driver/glmsync/src/zksync/faucet.rs
  core/payment-driver/gnt/Cargo.toml
  core/payment-driver/gnt/src/gnt/faucet.rs
  core/payment-driver/zksync/src/zksync/faucet.rs
  utils/networking/Cargo.toml
  utils/networking/src/lib.rs
  utils/networking/src/resolver.rs
  utils/networking/src/srv_resolver.rs
Labels: beta.1, bug, m-payment

#1071 Fallback for failing DNS resolution
  core/payment-driver/glmsync/src/zksync/faucet.rs
  core/payment-driver/gnt/src/gnt/faucet.rs
  core/payment-driver/zksync/src/zksync/faucet.rs
  utils/networking/src/resolver.rs
Labels: beta.1, bug

#1072 ZkSync: Unlock wallet before withdrawal
  core/payment-driver/glmsync/src/driver.rs
  core/payment-driver/glmsync/src/zksync/wallet.rs
  core/payment-driver/zksync/src/zksync/wallet.rs
Labels: beta.1, bug, m-payment

#1077 ZkSync: Fixed token name in withdraw
  core/payment-driver/zksync/examples/withdrawal.rs
  core/payment-driver/zksync/src/zksync/wallet.rs
Labels: beta.1, bug, m-payment

#1035 Market - reject agreement
  .github/workflows/rust.yml
  core/market/src/db/dao/agreement.rs
  core/market/src/db/dao/agreement_events.rs
  core/market/src/db/dao/negotiation_events.rs
  core/market/src/db/model/agreement_events.rs
  core/market/src/db/model/negotiation_events.rs
  core/market/src/negotiation/common.rs
  core/market/src/negotiation/error.rs
  core/market/src/negotiation/provider.rs
  core/market/src/negotiation/requestor.rs
  core/market/src/protocol/negotiation/error.rs
  core/market/src/protocol/negotiation/messages.rs
  core/market/src/protocol/negotiation/provider.rs
  core/market/src/protocol/negotiation/requestor.rs
  core/market/src/rest_api/error.rs
  core/market/src/rest_api/provider.rs
  core/market/src/testing/mock_node.rs
  core/market/tests/test_agreement.rs
  core/market/tests/test_agreement_events.rs
  core/market/tests/test_agreement_rejection.rs
  core/market/tests/test_negotiations.rs
  core/market/tests/test_rest_api.rs
Labels: t-mkt

#1044 Market - Cancel Agreement
  core/market/src/db/dao/agreement.rs
  core/market/src/db/dao/agreement_events.rs
  core/market/src/db/model/agreement_events.rs
  core/market/src/negotiation/common.rs
  core/market/src/negotiation/notifier.rs
  core/market/src/negotiation/provider.rs
  core/market/src/negotiation/requestor.rs
  core/market/src/protocol/negotiation/messages.rs
  core/market/src/protocol/negotiation/provider.rs
  core/market/src/protocol/negotiation/requestor.rs
  core/market/src/rest_api/requestor.rs
  core/market/src/testing/mock_node.rs
  core/market/tests/test_agreement_cancellation.rs
  core/market/tests/test_agreement_events.rs
  core/market/tests/test_rest_api.rs
Labels: t-mkt
